codecov:
  require_ci_to_pass: true
coverage:
  precision: 2
  range: 75..100
  status:
    patch:
      default:
        threshold: 20%
        if_not_found: success
    project:
      default:
        threshold: 10%
        if_not_found: success
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_base: false
  require_head: true
  require_changes: false
ignore:
  - './lib/base'
  - './lib/bean'
  - './lib/router'
  - './lib/util'
  - './lib/main.dart'
  - './lib/app_module.dart'
