name: Android-Publishment-build
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - name: Setup Flutter Credential
        run: flutter pub get
      - name: Run Flutter test
        run: flutter test
      - name: Setup Key Properties File
        run: |
          echo 'storePassword=${{ secrets.KEY_STORE_PASSWORD }}' >> android/key.properties
          echo 'keyPassword=${{ secrets.KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=key' >> android/key.properties
          echo 'storeFile=key.jks' >> android/key.properties
      - name: Decode KeyStore
        run: |
          echo ${{ secrets.SIGN_KEYSTORE }} | base64 -di > android/app/key.jks
      - name: Build Release apk
        run: flutter build apk
        id: build
        continue-on-error: true
      - name: Upload artifacts
        if: ${{ steps.build.outcome == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path:
            build/app/outputs/flutter-apk/app-release.apk
      - name: "Send Email Notification"
        if: ${{ steps.build.outcome == 'success' }}
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtpdm.aliyun.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github 构建结果提醒
          # Required recipients' addresses:
          to: ${{secrets.MAIL_RECEIVER}}
          # Required sender full name (address can be skipped):
          from: Rinrinko
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          # body: ${{github.actor}} 发起 Pull Request，请尽快进行 Code Review。
          # Using Markdown
          html_body: |
            ## ${{github.actor}} 触发流水线 APK 构建完毕，请及时查看测试验证
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
