name: Android-Development-build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - name: Setup Flutter Credential
        run: flutter pub get
      - name: Run Flutter test
        run: flutter test
      - name: Setup Key Properties File
          run: |
            echo 'storePassword=${{ secrets.KEY_STORE_PASSWORD }}' >> android/key.properties
            echo 'keyPassword=${{ secrets.KEY_PASSWORD }}' >> android/key.properties
            echo 'keyAlias=key' >> android/key.properties
            echo 'storeFile=key.jks' >> android/key.properties
      - name: Decode KeyStore
          run: |
            echo ${{ secrets.SIGN_KEYSTORE }} | base64 -di > android/app/key.jks
      - name: Build Debug apk
        run: flutter build apk --debug
        id: build
        continue-on-error: true
      - name: Upload artifacts
        if: ${{ steps.build.outcome == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: debug-artifacts
          path:
            build/app/outputs/flutter-apk/app-debug.apk
