name: iOS-Publishment-build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build-release-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - name: Setup Flutter Credential
        run: flutter pub get
      - name: Run Flutter test
        run: flutter test
      - name: Build Release ipa
        run: flutter build ios --release --no-codesign
        id: build
        continue-on-error: true
      - name: Upload artifacts
        if: ${{ steps.build.outcome == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: ${{ github.workspace }}/build/ios/**/*.app
